project:
  type: website
  output-dir: docs

website:
  title: "Zengtao Wang"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: file/Zengtao Wang_CV.pdf
        text: CV
      - research.qmd
      - Publications.qmd
      - Personal.qmd
      - post.qmd

format:
  html:
    theme:
      light: cosmo
      dark: solar
    css: styles.css
    toc: true
    page-layout: full

editor: visual

