---
title: "Publications"
format:
  html:
    toc: false
    number-sections: false
---

## Selected Publications

### **QSP Modeling Shows Pathological Synergism Between Insulin Resistance and Amyloid-Beta Exposure in Upregulating VCAM1 Expression at the BBB Endothelium.**

Wang Z, Veerareddy V, Tang X, Thompson KJ, Krishnan S, Kalari KR, Kandimalla KK. (2024)\
*CPT Pharmacometrics Syst Pharmacol.*\
[DOI: 10.1002/psp4.13296](https://ascpt.onlinelibrary.wiley.com/doi/full/10.1002/psp4.13296)

------------------------------------------------------------------------

### **High-Density Lipoprotein Mimetic Peptide 4F Reduces Toxic Amyloid-Beta Exposure to the Blood-Brain Barrier Endothelium in Alzheimer's Disease Transgenic Mice.**

Wang Z, Zhong R, Curran GL, Min P, Lowe VJ, Li L, Kandimalla KK. (2024)\
*Mol Pharm.*\
[DOI: 10.1021/acs.molpharmaceut.4c00633](https://pubs.acs.org/doi/full/10.1021/acs.molpharmaceut.4c00633)

------------------------------------------------------------------------

### **Amyloid-beta proteins 40 and 42 employ distinct molecular pathways for cell entry and intracellular transit at the BBB endothelium.**

Wang Z, Sharda N, Omtri RS, Li L, Kandimalla KK. (2023)\
*Mol Pharmacol.*\
[DOI: 10.1124/molpharm.123.000670](https://molpharm.aspetjournals.org/article/S0026-895X(24)00059-2/abstract)

------------------------------------------------------------------------

### **Deconvolution of plasma pharmacokinetics from dynamic heart imaging data obtained by SPECT/CT imaging.**

Wang Z, Wang L, Ebbini M, Curran GL, Vernon CJ, Min HK, Siegel RA, Lowe VJ, Kandimalla KK. (2023)\
*J Pharmacol Exp Ther.*\
[DOI: 10.1124/jpet.122.001545](https://jpet.aspetjournals.org/article/S0022-3565(24)17050-4/abstract)

------------------------------------------------------------------------

### **Mapping the Dynamics of Insulin-responsive Pathways in the Blood Brain Barrier Endothelium using Time-series Transcriptomics Data.**

Wang Z, Tang X, Swaminathan SK, Kalari KR, Kandimalla KK. (2022)\
*NPJ Syst Biol Appl.*\
[DOI: 10.1038/s41540-022-00288-0](https://www.nature.com/articles/s41540-022-00235-8)

------------------------------------------------------------------------

### **Semimechanistic Population Pharmacokinetic Modeling to Investigate Amyloid Beta Trafficking and Accumulation at the BBB Endothelium.**

Wang Z, Sharda N, Curran GL, Li L, Lowe VJ, Kandimalla KK. (2021)\
*Mol Pharm.*\
[DOI: 10.1021/acs.jmedchem.8b01633](https://pubs.acs.org/doi/10.1021/acs.jmedchem.8b01633)

------------------------------------------------------------------------

### **Design, Synthesis, and Biological Evaluation of Cytochrome P450 1B1 Targeted Molecular Imaging Probes for Colorectal Tumor Detection.**

Meng Q, Wang Z, Cui J, Cui Q, Dong J, Zhang Q, Li S. (2018)\
*J Med Chem.*\
[DOI: 10.1021/acs.jmedchem.8b00707](https://pubs.acs.org/doi/10.1021/acs.jmedchem.8b00707)


## Full List

📄 View all publications on [Google Scholar](https://scholar.google.com/citations?user=4mJXDH4AAAAJ&hl=en)
